// Credenciais do Supabase
export const PROJECT_URL = "https://lrfdwafpsjuiqiovrfnk.supabase.co";
export const API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyZmR3YWZwc2p1aXFpb3ZyZm5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE2NzgwMTcsImV4cCI6MjA0NzI1NDAxN30.IDdX57VVPoDgJU4VcMISTpAhQ5f1SBSJDm5kfSd1WUI";